name: mlflow-env
channels:
  - defaults
  - pytorch
  - conda-forge

dependencies:
  - python=3.9
  - cudatoolkit=11.8
  - pip
  - numpy=1.23.5
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - matplotlib=3.9.2
  - pip:
      - pytest~=8.3.4
      - lxml~=4.9.4
      - beautifulsoup4~=4.12.3
      - soupsieve~=2.6
      - packaging~=24.1
      - typing_extensions~=4.12.2
      - html5lib~=1.1
      - jupyter~=1.0.0
      - pip~=25.0.1
      - attrs~=24.2.0
      - distro~=1.9.0
      - wheel~=0.45.1
      - pillow~=11.0.0
      - filelock~=3.17.0
      - pyzmq~=26.4.0
      - colorama~=0.4.6
      - cffi~=1.17.1
      - tornado~=6.1
      - setuptools~=70.0.0
      - bleach~=6.1.0
      - webencodings~=0.5.1
      - tinycss2~=1.2.1
      - MarkupSafe~=2.1.3
      - six~=1.16.0
      - python-dateutil~=2.9.0.post0
      - nbformat~=5.9.2
      - jupyter_core~=5.5.0
      - traitlets~=5.14.0
      - nbclient~=0.9.0
      - jupyter_client~=8.6.0
      - fastjsonschema~=2.19.0
      - jsonschema~=4.20.0
      - Pygments~=2.17.2
      - ipython~=8.18.1
      - nbconvert~=7.11.0
      - pandocfilters~=1.5.0
      - defusedxml~=0.7.1
      - mistune~=3.0.2
      - Jinja2~=3.1.2
      - notebook~=7.2.2
      - PyQt5~=5.15.11
      - jupyterlab_pygments~=0.3.0
      - referencing~=0.31.1
      - idna~=3.10
      - webcolors~=1.13
      - jsonpointer~=2.4
      - isoduration~=20.11.0
      - fqdn~=1.5.1
      - pyparsing~=3.2.0
      - platformdirs~=4.3.6
      - selenium~=4.27.1
      - executing~=2.0.1
      - fonttools~=4.54.1
      - ipykernel~=6.27.1
      - pycparser~=2.21
      - qtconsole~=5.5.1
      - websocket-client~=1.8.0
      - terminado~=0.18.0
      - websockets~=13.1
      - cycler~=0.12.1
      - kiwisolver~=1.4.7
      - Send2Trash~=1.8.2
      - click~=8.1.3
      - jupyter_server_terminals~=0.4.4
      - anyio~=4.6.2.post1
      - orjson~=3.10.15
      - gradio~=5.23.2
      - mlflow~=2.21.3
      - dotenv~=0.9.9
      - python-dotenv~=1.1.0
      - tqdm~=4.67.1
      - joblib~=1.4.2
      - fsspec~=2025.3.0
      - aiohttp~=3.10.10
      - yarl~=1.16.0
      - requests~=2.32.3
      - rich~=13.7.1
      - psutil~=5.9.6
      - urllib3~=2.2.3
      - certifi~=2024.8.30
      - debugpy~=1.8.0
      - greenlet~=3.2.1
      - SQLAlchemy~=2.0.23
      - deprecation~=2.1.0
      - h2~=4.1.0
      - networkx~=3.2
      - jupyter_server~=2.11.1
      - jupyterlab~=4.2.5
      - jupyterlab_server~=2.27.3
      - notebook_shim~=0.2.3
      - asttokens~=2.4.1
      - contourpy~=1.3.0
      - trio~=0.28.0
      - outcome~=1.3.0.post0
      - arrow~=1.3.0
      - Babel~=2.13.1
      - pytz~=2024.2
      - json5~=0.9.14
      - overrides~=7.4.0
      - scipy~=1.15.2
      - threadpoolctl~=3.6.0
      - mpmath~=1.3.0
      - sympy~=1.13.1
      - decorator~=5.1.1
      - tabulate~=0.9.0
      - pluggy~=1.5.0
      - iniconfig~=2.0.0
      - sniffio~=1.3.1
