name: Train and Deploy Pipeline

on:
  push:
    branches:
      - production  # trigger on production push

jobs:
  train:
    name: Train Model
    runs-on: [self-hosted, max-pc]  # run on max pc for gpu usage
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Training Script
        run: |
          python train.py

      - name: Upload Trained Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model_artifacts/model.pt

  deploy:
    name: Deploy Model to Hugging Face
    needs: train   # require train completion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install huggingface_hub

      - name: Download Trained Model Artifact
        uses: actions/download-artifact@v4
        with:
          name: model
          path: model_artifacts/

      - name: Deploy to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python deploy_to_hf.py
