name: Deploy to Hugging Face

on:
  repository_dispatch:
    types: [trigger-deployment]  # trigger on evaluation success

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install huggingface_hub

      - name: Deploy Model
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python deploy_to_hf.py
