name: Train Model

on:
  push:
    tags:
      - 'train-v*'  # trigger tagged push

jobs:
  train:
    runs-on: [self-hosted, max-pc-runner] # run on max pc for gpu usage

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu118
          pip install -r requirements.txt

      - name: Run Training Script
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_PASSWORD }}
        run: python train.py
